# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 321904a0a2a87e0a84a03443d96e941d1cc25a28a8419fb5dd542715df2bfbd2f6971c2e39109c8b43a138930d76641f6c8ccffbec142ca8f6de311b301c19c4

test:
  secret_key_base: de01a90665ca04f74493ce62b3079c761786b343fd5cb354a9b4cc7b11d01f6deffef82ec60f1652f8f30b123c4f40abc3a950600923c12e897abbb9af1b3d31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
